/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.76
 * Generated at: 2018-05-02 01:01:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.page;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class userRegister_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"zh-CN\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no\">\r\n");
      out.write("<title>购衣系统注册</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/ShoppingMall/css/style.css\">\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"register-container\">\r\n");
      out.write("\t<h1>*****User-Register*****</h1>\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"connect\">\r\n");
      out.write("\t\t<p>Link the world. Share to world.</p>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<form action=\"\" method=\"\" id=\"registerForm\">\r\n");
      out.write("\t\t<div>\r\n");
      out.write("\t\t\t<input type=\"text\" name=\"role_name\" class=\"username\" placeholder=\"您的用户名\" autocomplete=\"off\" id=\"role_name\"/>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div>\r\n");
      out.write("\t\t\t<input type=\"password\" name=\"role_pwd\" class=\"password\" placeholder=\"输入密码\" oncontextmenu=\"return false\" onpaste=\"return false\" id=\"role_pwd\"/>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div>\r\n");
      out.write("\t\t\t<input type=\"password\" name=\"pwd_again\" class=\"confirm_password\" placeholder=\"再次输入密码\" oncontextmenu=\"return false\" onpaste=\"return false\" id=\"pwd_again\"/>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div>\r\n");
      out.write("\t\t\t<input type=\"text\" name=\"role_tel\" class=\"phone_number\" placeholder=\"输入手机号码\" autocomplete=\"off\" id=\"role_tel\"/>\r\n");
      out.write("\t\t\t<input type=\"button\" value=\"获取验证码\" onclick=\"getYzm()\" style=\"cursor: pointer;\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div>\r\n");
      out.write("\t\t\t<input type=\"text\" name=\"role_yzm\" class=\"phone_yzm\" placeholder=\"输入验证码\" autocomplete=\"off\" id=\"yzm\"/>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t<button id=\"register\" type=\"submit\" onclick=\"selRegister()\">注 册</button>\r\n");
      out.write("\t</form>\r\n");
      out.write("\t<a href=\"/ShoppingMall/page/roleLogin.jsp\">\r\n");
      out.write("\t\t<button type=\"button\" class=\"register-tis\">已经有账号？</button>\r\n");
      out.write("\t</a>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("<script src=\"/ShoppingMall/js/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"/ShoppingMall/js/common.js\"></script>\r\n");
      out.write("<!--背景图片自动更换-->\r\n");
      out.write("<script src=\"/ShoppingMall/js/supersized.3.2.7.min.js\"></script>\r\n");
      out.write("<script src=\"/ShoppingMall/js/supersized-init.js\"></script>\r\n");
      out.write("<!--表单验证-->\r\n");
      out.write("<script src=\"/ShoppingMall/js/jquery.validate.min.js?var1.14.0\"></script>\r\n");
      out.write("<!-- ajax发送验证码 -->\r\n");
      out.write("<script src=\"/ShoppingMall/js/jquery-3.2.1.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/ShoppingMall/js/jquery.form.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tvar xmlHttp;\r\n");
      out.write("\tfunction createXmlHttpRequest(){\r\n");
      out.write("\t\tif(window.ActiveXObject){\r\n");
      out.write("\t\t\txmlHttp=new ActiveXObject(\"Microsoft.XMLHTTP\");\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\txmlHttp=new XMLHttpRequest();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction handleStateChange(){\r\n");
      out.write("\t\tif(xmlHttp.readyState==4){\r\n");
      out.write("\t\t\tif(xmlHttp.status==200){\r\n");
      out.write("\t\t\t\tvar result=xmlHttp.responseText;\r\n");
      out.write("\t\t\t\talert(result);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction createSendData(){\r\n");
      out.write("\t\tvar role_name=document.getElementById(\"role_name\").value;\r\n");
      out.write("\t\tvar role_tel=document.getElementById(\"role_tel\").value;\r\n");
      out.write("\t\tvar data=\"rolename=\"+role_name+\"&roletel=\"+role_tel;\r\n");
      out.write("\t\treturn data;\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction getYzm(){\r\n");
      out.write("\t\talert(\"短信已发送，请注意查收\");\r\n");
      out.write("\t\tvar role_name=document.getElementById(\"role_name\").value;\r\n");
      out.write("\t\tvar role_tel=document.getElementById(\"role_tel\").value;\r\n");
      out.write("\t\tif(role_name==null||role_name==\"\"){\r\n");
      out.write("\t\t\talert(\"请输入用户名\");\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\t if(role_tel==null||role_tel==\"\"){\r\n");
      out.write("\t\t\t\talert(\"请输入手机号码\");\r\n");
      out.write("\t\t\t}else{ \r\n");
      out.write("\t\t\t\tcreateXmlHttpRequest();\r\n");
      out.write("\t\t\t\tvar url=\"/ShoppingMall/user/getyzm.do\";\r\n");
      out.write("\t\t\t\txmlHttp.open(\"get\", url+\"?\"+createSendData());\r\n");
      out.write("\t\t\t\txmlHttp.setRequestHeader(\"Content-Type\", \"application/x-www-form-urlencoded\");\r\n");
      out.write("\t\t\t\txmlHttp.send(null);\r\n");
      out.write("\t\t\t\txmlHttp.onreadystatechange=handleStateChange();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction selRegister(){\r\n");
      out.write("\t\tvar role_name=document.getElementById(\"role_name\").value;\r\n");
      out.write("\t\tvar role_pwd=document.getElementById(\"role_pwd\").value;\r\n");
      out.write("\t\tvar pwd_again=document.getElementById(\"pwd_again\").value;\r\n");
      out.write("\t\tvar role_tel=document.getElementById(\"role_tel\").value;\r\n");
      out.write("\t\tvar yzm=document.getElementById(\"yzm\").value;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(role_name==null||role_name==\"\"){\r\n");
      out.write("\t\t\talert(\"请输入用户名\");\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\tif(role_pwd==null||role_pwd==\"\"){\r\n");
      out.write("\t\t\t\talert(\"请输入密码\");\r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t\t\tif(pwd_again==null||pwd_again==\"\"){\r\n");
      out.write("\t\t\t\t\talert(\"请再次输入密码\");\r\n");
      out.write("\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\tif(role_pwd!=pwd_again){\r\n");
      out.write("\t\t\t\t\t\talert(\"两次输入的密码不一致\");\r\n");
      out.write("\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\tif(role_tel==null||role_tel==\"\"){\r\n");
      out.write("\t\t\t\t\t\t\talert(\"请输入手机号码\");\r\n");
      out.write("\t\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\t\tif(yzm==null||yzm==\"\"){\r\n");
      out.write("\t\t\t\t\t\t\t\talert(\"请输入验证码\");\r\n");
      out.write("\t\t\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById(\"registerForm\").action=\"/ShoppingMall/user/userRegist.do\";\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById(\"registerForm\").method=\"post\";\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById(\"registerForm\").submit();\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
