/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.76
 * Generated at: 2018-05-05 08:38:36 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.page.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class adminPage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>管理员首页</title>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\tbody {\r\n");
      out.write("\tbackground: url(\"/ShoppingMall/img/adminbg.jpg\") no-repeat;\r\n");
      out.write("\tbackground-size:cover; \r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t\t<center>\r\n");
      out.write("\t\t\t<img alt=\"用户头像\" src=\"/ShoppingMall/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.currvalRole.role_head}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\">\r\n");
      out.write("\t\t\t<span>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.currvalRole.role_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</span>\r\n");
      out.write("\t\t</center>\r\n");
      out.write("\t\t<p>\r\n");
      out.write("\t\t\t<a href=\"/ShoppingMall/index.jsp\">回到首页</a>\r\n");
      out.write("\t\t</p>\r\n");
      out.write("\t\t<p>\r\n");
      out.write("\t\t\t<form action=\"/ShoppingMall/admin/loginOut.do\" method=\"get\">\r\n");
      out.write("\t\t\t\t<input type=\"submit\" value=\"退出登录\">\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t</p>\r\n");
      out.write("\t\t<p>\r\n");
      out.write("\t\t\t<form action=\"/ShoppingMall/admin/queryGoodByName.do\" method=\"post\" target=\"_blank\">\r\n");
      out.write("\t\t\t\t<input type=\"text\" placeholder=\"请输入商品名关键字...\" name=\"good_name\">\r\n");
      out.write("\t\t\t\t<input type=\"submit\" value=\"搜索商品\" style=\"cursor: pointer\">\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t</p>\r\n");
      out.write("\t\t<p>\r\n");
      out.write("\t\t<form action=\"/ShoppingMall/admin/queryRoleById.do\" method=\"post\" target=\"_blank\">\r\n");
      out.write("\t\t\t<input type=\"text\" placeholder=\"请输入角色id...\" name=\"role_id\">\r\n");
      out.write("\t\t\t<input type=\"submit\" value=\"查找\">\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t\t</p>\r\n");
      out.write("\t\t<p>\r\n");
      out.write("\t\t<form action=\"/ShoppingMall/admin/queryRoleByName.do\" method=\"post\" target=\"_blank\">\r\n");
      out.write("\t\t\t<input type=\"text\" placeholder=\"请输入角色名...\" name=\"role_name\">\r\n");
      out.write("\t\t\t<input type=\"submit\" value=\"查找\">\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t\t</p>\r\n");
      out.write("\t\t<p>\r\n");
      out.write("\t\t<form action=\"/ShoppingMall/admin/adminLookGood.do\" method=\"get\" target=\"_blank\">\r\n");
      out.write("\t\t\t<input type=\"submit\" value=\"浏览商品\" style=\"cursor: pointer\">\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t\t</p>\r\n");
      out.write("\t\t<p>\r\n");
      out.write("\t\t<form action=\"/ShoppingMall/admin/adminLookStore.do\" method=\"get\" target=\"_blank\">\r\n");
      out.write("\t\t\t<input type=\"submit\" value=\"浏览店铺\" style=\"cursor: pointer\">\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t\t</p>\r\n");
      out.write("\t\t<p>\r\n");
      out.write("\t\t<form action=\"/ShoppingMall/admin/lookApplyStore.do\" method=\"get\" target=\"_blank\">\r\n");
      out.write("\t\t\t<input type=\"submit\" value=\"查看申请开店\" style=\"cursor: pointer\">\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t\t</p>\r\n");
      out.write("\t\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
