/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.76
 * Generated at: 2018-04-15 08:29:10 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.page.user;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class userPays_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("    <title>支付首页</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.payResult}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\r\n");
      out.write("\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("<!-- Jquery files -->\r\n");
      out.write("<!-- <script type=\"text/javascript\" src=\"https://cdn.staticfile.org/jquery/1.11.1/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"js/jquery-3.2.1.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/jquery.form.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\"> \r\n");
      out.write(" $().ready(function(){\r\n");
      out.write("    function getistype(){\r\n");
      out.write("        return ($(\"#demo1-alipay\").is(':checked') ? \"1\" : \"2\" ); \r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    $(\"#demoBtn1\").click(function(){\r\n");
      out.write("    \talert(\"触发支付\");\r\n");
      out.write("    \tvar options={\r\n");
      out.write("    \t\t\turl:\"/ShoppingMall/pays/pay.do\",\r\n");
      out.write("    \t\t\ttype:\"post\",\r\n");
      out.write("    \t\t\tdataType:\"json\",\r\n");
      out.write("    \t\t\tprice : $(\"#inputprice\").val(), \r\n");
      out.write("                istype : getistype(),\r\n");
      out.write("                success:function(data){\r\n");
      out.write("                \tif (data.code > 0){\r\n");
      out.write("                        $(\"#goodsname\").val(data.data.goodsname);\r\n");
      out.write("                        $(\"#istype\").val(data.data.istype);\r\n");
      out.write("                        $('#key').val(data.data.key);\r\n");
      out.write("                        $('#notify_url').val(data.data.notify_url);\r\n");
      out.write("                        $('#orderid').val(data.data.orderid);\r\n");
      out.write("                        $('#orderuid').val(data.data.orderuid);\r\n");
      out.write("                        $('#price').val(data.data.price);\r\n");
      out.write("                        $('#return_url').val(data.data.return_url);\r\n");
      out.write("                        $('#uid').val(data.data.uid);\r\n");
      out.write("                        $('#submitdemo1').click();\r\n");
      out.write("                    } else {\r\n");
      out.write("                        alert(data.msg);\r\n");
      out.write("                    }\r\n");
      out.write("                }\r\n");
      out.write("    \t};\r\n");
      out.write("        $.post(\r\n");
      out.write("            \"/ShoppingMall/pays/pay.do\",\r\n");
      out.write("            {\r\n");
      out.write("                price : $(\"#inputprice\").val(), \r\n");
      out.write("                istype : getistype(),\r\n");
      out.write("            },\r\n");
      out.write("            function(data){ \r\n");
      out.write("                if (data.code > 0){\r\n");
      out.write("                    $(\"#goodsname\").val(data.data.goodsname);\r\n");
      out.write("                    $(\"#istype\").val(data.data.istype);\r\n");
      out.write("                    $('#key').val(data.data.key);\r\n");
      out.write("                    $('#notify_url').val(data.data.notify_url);\r\n");
      out.write("                    $('#orderid').val(data.data.orderid);\r\n");
      out.write("                    $('#orderuid').val(data.data.orderuid);\r\n");
      out.write("                    $('#price').val(data.data.price);\r\n");
      out.write("                    $('#return_url').val(data.data.return_url);\r\n");
      out.write("                    $('#uid').val(data.data.uid);\r\n");
      out.write("                    $('#submitdemo1').click();\r\n");
      out.write("                } else {\r\n");
      out.write("                    alert(data.msg);\r\n");
      out.write("                }\r\n");
      out.write("            }, \"json\"\r\n");
      out.write("        ); \r\n");
      out.write("    $(\"#demoBtn1\").ajaxSubmit(options);\r\n");
      out.write("    });\r\n");
      out.write("    \r\n");
      out.write("}); \r\n");
      out.write("</script>  -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
