/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.76
 * Generated at: 2018-05-05 02:42:30 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.page.store;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class queryReportData_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>查看报表</title>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\t#startDiv{\r\n");
      out.write("\t\tposition: absolute;\r\n");
      out.write("\t\ttop:100px;\r\n");
      out.write("\t\tleft:20px;\r\n");
      out.write("\t}\r\n");
      out.write("\t#endDiv{\r\n");
      out.write("\t\tposition: absolute;\r\n");
      out.write("\t\ttop:100px;\r\n");
      out.write("\t\tleft: 300px;\r\n");
      out.write("\t}\r\n");
      out.write("\t#query{\r\n");
      out.write("\t\tposition: absolute;\r\n");
      out.write("\t\ttop:100px;\r\n");
      out.write("\t\tleft: 550px;\r\n");
      out.write("\t}\r\n");
      out.write("\t#lookReportData{\r\n");
      out.write("\t\tposition: absolute;\r\n");
      out.write("\t\ttop:150px;\r\n");
      out.write("\t\tleft:20px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("body {\r\n");
      out.write("\tbackground: url(\"/ShoppingMall/img/storebg.jpg\") no-repeat;\r\n");
      out.write("\tbackground-size:cover; \r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<center>\r\n");
      out.write("\t<h2>查看报表数据</h2>\r\n");
      out.write("</center>\r\n");
      out.write("<form action=\"/ShoppingMall/store/storeLookReportData.do\" method=\"post\">\r\n");
      out.write("<div id=\"startDiv\">\r\n");
      out.write("开始时间\r\n");
      out.write("<select id=\"startDateData\" name=\"start_date\">\r\n");
      out.write("\t<option value=\"\">-请选择-</option>\r\n");
      out.write("\t<option value=\"2017年11月01号00:00:00\">2017年11月01号00:00:00</option>\r\n");
      out.write("\t<option value=\"2017年12月01号00:00:00\">2017年12月01号00:00:00</option>\r\n");
      out.write("\t<option value=\"2018年01月01号00:00:00\">2018年01月01号00:00:00</option>\r\n");
      out.write("\t<option value=\"2018年02月01号00:00:00\">2018年02月01号00:00:00</option>\r\n");
      out.write("\t<option value=\"2018年03月01号00:00:00\">2018年03月01号00:00:00</option>\r\n");
      out.write("\t<option value=\"2018年04月01号00:00:00\">2018年04月01号00:00:00</option>\r\n");
      out.write("\t<option value=\"2018年05月01号00:00:00\">2018年05月01号00:00:00</option>\r\n");
      out.write("\t<option value=\"2018年06月01号00:00:00\">2018年06月01号00:00:00</option>\r\n");
      out.write("\t<option value=\"2018年07月01号00:00:00\">2018年07月01号00:00:00</option>\r\n");
      out.write("\t<option value=\"2018年08月01号00:00:00\">2018年08月01号00:00:00</option>\r\n");
      out.write("\t<option value=\"2018年09月01号00:00:00\">2018年09月01号00:00:00</option>\r\n");
      out.write("\t<option value=\"2018年10月01号00:00:00\">2018年10月01号00:00:00</option>\r\n");
      out.write("\t<option value=\"2018年11月01号00:00:00\">2018年11月01号00:00:00</option>\r\n");
      out.write("\t<option value=\"2018年12月01号00:00:00\">2018年12月01号00:00:00</option>\r\n");
      out.write("\t<option value=\"2019年01月01号00:00:00\">2019年01月01号00:00:00</option>\r\n");
      out.write("\t<option value=\"2019年02月01号00:00:00\">2019年02月01号00:00:00</option>\r\n");
      out.write("\t<option value=\"2019年03月01号00:00:00\">2019年03月01号00:00:00</option>\r\n");
      out.write("\t<option value=\"2019年04月01号00:00:00\">2019年04月01号00:00:00</option>\r\n");
      out.write("\t<option value=\"2019年05月01号00:00:00\">2019年05月01号00:00:00</option>\r\n");
      out.write("\t<option value=\"2019年06月01号00:00:00\">2019年06月01号00:00:00</option>\r\n");
      out.write("\t<option value=\"2019年07月01号00:00:00\">2019年07月01号00:00:00</option>\r\n");
      out.write("\t<option value=\"2019年08月01号00:00:00\">2019年08月01号00:00:00</option>\r\n");
      out.write("\t<option value=\"2019年09月01号00:00:00\">2019年09月01号00:00:00</option>\r\n");
      out.write("\t<option value=\"2019年10月01号00:00:00\">2019年10月01号00:00:00</option>\r\n");
      out.write("\t<option value=\"2019年11月01号00:00:00\">2019年11月01号00:00:00</option>\r\n");
      out.write("\t<option value=\"2019年12月01号00:00:00\">2019年12月01号00:00:00</option>\r\n");
      out.write("</select>\r\n");
      out.write("</div>\r\n");
      out.write("<div id=\"endDiv\">\r\n");
      out.write("结束时间\r\n");
      out.write("<select id=\"endDateData\" name=\"end_date\">\r\n");
      out.write("\t<option value=\"\">-请选择-</option>\r\n");
      out.write("\t<option value=\"2017年11月01号00:00:00\">2017年11月01号00:00:00</option>\r\n");
      out.write("\t<option value=\"2017年12月01号00:00:00\">2017年12月01号00:00:00</option>\r\n");
      out.write("\t<option value=\"2018年01月01号00:00:00\">2018年01月01号00:00:00</option>\r\n");
      out.write("\t<option value=\"2018年02月01号00:00:00\">2018年02月01号00:00:00</option>\r\n");
      out.write("\t<option value=\"2018年03月01号00:00:00\">2018年03月01号00:00:00</option>\r\n");
      out.write("\t<option value=\"2018年04月01号00:00:00\">2018年04月01号00:00:00</option>\r\n");
      out.write("\t<option value=\"2018年05月01号00:00:00\">2018年05月01号00:00:00</option>\r\n");
      out.write("\t<option value=\"2018年06月01号00:00:00\">2018年06月01号00:00:00</option>\r\n");
      out.write("\t<option value=\"2018年07月01号00:00:00\">2018年07月01号00:00:00</option>\r\n");
      out.write("\t<option value=\"2018年08月01号00:00:00\">2018年08月01号00:00:00</option>\r\n");
      out.write("\t<option value=\"2018年09月01号00:00:00\">2018年09月01号00:00:00</option>\r\n");
      out.write("\t<option value=\"2018年10月01号00:00:00\">2018年10月01号00:00:00</option>\r\n");
      out.write("\t<option value=\"2018年11月01号00:00:00\">2018年11月01号00:00:00</option>\r\n");
      out.write("\t<option value=\"2018年12月01号00:00:00\">2018年12月01号00:00:00</option>\r\n");
      out.write("\t<option value=\"2019年01月01号00:00:00\">2019年01月01号00:00:00</option>\r\n");
      out.write("\t<option value=\"2019年02月01号00:00:00\">2019年02月01号00:00:00</option>\r\n");
      out.write("\t<option value=\"2019年03月01号00:00:00\">2019年03月01号00:00:00</option>\r\n");
      out.write("\t<option value=\"2019年04月01号00:00:00\">2019年04月01号00:00:00</option>\r\n");
      out.write("\t<option value=\"2019年05月01号00:00:00\">2019年05月01号00:00:00</option>\r\n");
      out.write("\t<option value=\"2019年06月01号00:00:00\">2019年06月01号00:00:00</option>\r\n");
      out.write("\t<option value=\"2019年07月01号00:00:00\">2019年07月01号00:00:00</option>\r\n");
      out.write("\t<option value=\"2019年08月01号00:00:00\">2019年08月01号00:00:00</option>\r\n");
      out.write("\t<option value=\"2019年09月01号00:00:00\">2019年09月01号00:00:00</option>\r\n");
      out.write("\t<option value=\"2019年10月01号00:00:00\">2019年10月01号00:00:00</option>\r\n");
      out.write("\t<option value=\"2019年11月01号00:00:00\">2019年11月01号00:00:00</option>\r\n");
      out.write("\t<option value=\"2019年12月01号00:00:00\">2019年12月01号00:00:00</option>\r\n");
      out.write("</select>\r\n");
      out.write("</div>\r\n");
      out.write("<div id=\"query\">\r\n");
      out.write("<input type=\"submit\" value=\"查询\">\r\n");
      out.write("</div>\r\n");
      out.write("</form>\r\n");
      out.write("<!-- <div id=\"lookReportData\">\r\n");
      out.write("\t<iframe src=\"/ShoppingMall/page/store/lookReportData.jsp\"></iframe>\r\n");
      out.write("</div> -->\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
