/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.76
 * Generated at: 2018-04-26 03:40:10 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.page.store;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class storeRegist_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>店铺注册</title>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\tbody {\r\n");
      out.write("\tbackground: url(\"/ShoppingMall/img/storebg.jpg\") no-repeat;\r\n");
      out.write("\tbackground-size:cover; \r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t<div style=\"margin-left: 30px; margin-top: 30px\">\r\n");
      out.write("\t\t<form action=\"\" method=\"post\" enctype=\"\" id=\"storeRegist\">\r\n");
      out.write("\t\t\t<div style=\"position:absolute; top:40px; left:38px;\">\r\n");
      out.write("\t\t\t<h3>店铺注册</h3>\r\n");
      out.write("\t\t\t<p>\r\n");
      out.write("\t\t\t\t店铺名：<input name=\"role_name\" id=\"role_name\" required=\"required\">\r\n");
      out.write("\t\t\t</p>\r\n");
      out.write("\t\t\t<p>\r\n");
      out.write("\t\t\t\t店铺密码：<input name=\"role_pwd\" required=\"required\" id=\"role_pwd\">\r\n");
      out.write("\t\t\t</p>\r\n");
      out.write("\t\t\t<p>\r\n");
      out.write("\t\t\t\t店铺联系人：<input name=\"linkman_name\" required=\"required\" id=\"linkman_name\">\r\n");
      out.write("\t\t\t</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<p style=\"position:absolute; top:200px; left:38px\">\r\n");
      out.write("\t\t\t\t<input name=\"role_tel\" id=\"role_tel\" placeholder=\"输入手机号码\" required=\"required\">\r\n");
      out.write("\t\t\t\t<input type=\"button\" value=\"获取验证码\" onclick=\"getYzm()\" style=\"cursor: pointer;\">\r\n");
      out.write("\t\t\t</p>\r\n");
      out.write("\t\t\t<p style=\"position:absolute; top:240px; left:38px\">\r\n");
      out.write("\t\t\t\t请输入收到的验证码：<input name=\"role_yzm\" placeholder=\"输入验证码\" required=\"required\"/>\r\n");
      out.write("\t\t\t</p>\r\n");
      out.write("\t\t\t<div style=\"position:absolute; top:280px; left:38px;\">\r\n");
      out.write("\t\t\t<p>\r\n");
      out.write("\t\t\t\t店铺营业执照图片路径<input id=\"storeLicenseRoute\" name=\"store_license\" type=\"text\" value=\"\" style=\"width: 400px\" hidden=\"hidden\">\r\n");
      out.write("\t\t\t</p>\r\n");
      out.write("\t\t\t<p>\r\n");
      out.write("\t\t\t\t店主手持身份证图片路径<input id=\"storeMenRoute\" name=\"store_men_image\" type=\"text\" value=\"\" style=\"width: 400px\" hidden=\"hidden\">\r\n");
      out.write("\t\t\t</p>\r\n");
      out.write("\t\t\t<p>\r\n");
      out.write("\t\t\t\t店铺图片路径<input id=\"storeImageRoute\" name=\"store_image\" type=\"text\" value=\"\" style=\"width: 400px\" hidden=\"hidden\">\r\n");
      out.write("\t\t\t</p>\r\n");
      out.write("\t\t\t<p>\r\n");
      out.write("\t\t\t\t<input type=\"submit\" value=\"注册店铺\" onclick=\"selStoreRegist()\">\r\n");
      out.write("\t\t\t</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t\t<div style=\"position: absolute; top: 50px; left: 800px;\">\r\n");
      out.write("\t\t\t\t\t上传店主手持身份证照片\r\n");
      out.write("\t\t\t\t\t<form action=\"\" method=\"post\" enctype=\"multipart/form-data\" id=\"uploadStoreMen\">\r\n");
      out.write("\t\t\t\t\t\t<input id=\"changeStoreMen\" type=\"file\" onchange=\"uploadStoreMen()\" name=\"storeMenImage\"\r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"position: absolute; z-index: 10; opacity: 0; width: 100px; height: 100px;\">\r\n");
      out.write("\t\t\t\t\t\t<img id=\"defaultStoreMen\" src=\"/ShoppingMall/upload/defaultHead.png\" title=\"点击上传图片\"\r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"position: absolute; z-index: 9; float: left; width: 100px; height: 100px\"><br>\r\n");
      out.write("\t\t\t\t\t\t\t点击上传图片\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div style=\"position: absolute; top: 200px; left: 800px;\">\r\n");
      out.write("\t\t\t\t\t上传营业执照照片\r\n");
      out.write("\t\t\t\t\t<form action=\"\" method=\"post\" enctype=\"multipart/form-data\" id=\"uploadStoreLicense\">\r\n");
      out.write("\t\t\t\t\t\t<input id=\"changeStoreLicense\" type=\"file\" onchange=\"uploadStoreLicense()\" name=\"storeLicenseImage\"\r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"position: absolute; z-index: 10; opacity: 0; width: 100px; height: 100px;\">\r\n");
      out.write("\t\t\t\t\t\t<img id=\"defaultStoreLicense\" src=\"/ShoppingMall/upload/defaultHead.png\" title=\"点击上传图片\"\r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"position: absolute; z-index: 9; float: left; width: 100px; height: 100px\"><br>\r\n");
      out.write("\t\t\t\t\t\t\t点击上传图片\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div style=\"position: absolute; top: 350px; left: 800px;\">\r\n");
      out.write("\t\t\t\t\t上传店铺图片\r\n");
      out.write("\t\t\t\t\t<form action=\"\" method=\"post\" enctype=\"multipart/form-data\" id=\"uploadStoreImage\">\r\n");
      out.write("\t\t\t\t\t\t<input id=\"changeStoreImage\" type=\"file\" onchange=\"uploadStoreImage()\" name=\"storeImage\"\r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"position: absolute; z-index: 10; opacity: 0; width: 100px; height: 100px;\">\r\n");
      out.write("\t\t\t\t\t\t<img id=\"defaultStoreImage\" src=\"/ShoppingMall/upload/defaultHead.png\" title=\"点击上传图片\"\r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"position: absolute; z-index: 9; float: left; width: 100px; height: 100px\"><br>\r\n");
      out.write("\t\t\t\t\t\t\t点击上传图片\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- <div style=\"position:absolute; top:210px; left:38px\">\r\n");
      out.write("\t\t\t<form action=\"\" method=\"post\" id=\"getYzm\">\r\n");
      out.write("\t\t\t\t\t请输入手机号：<input name=\"role_tel\">\r\n");
      out.write("\t\t\t\t\t<input type=\"submit\" value=\"获取验证码\" onclick=\"getyzm()\">\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t</div> -->\r\n");
      out.write("\t</div>\r\n");
      out.write("<script src=\"/ShoppingMall/js/jquery-3.2.1.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/ShoppingMall/js/jquery.form.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("var xmlHttp;\r\n");
      out.write("function createXmlHttpRequest(){\r\n");
      out.write("\tif(window.ActiveXObject){\r\n");
      out.write("\t\txmlHttp=new ActiveXObject(\"Microsoft.XMLHTTP\");\r\n");
      out.write("\t}else{\r\n");
      out.write("\t\txmlHttp=new XMLHttpRequest();\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("function handleStateChange(){\r\n");
      out.write("\tif(xmlHttp.readyState==4){\r\n");
      out.write("\t\tif(xmlHttp.status==200){\r\n");
      out.write("\t\t\tvar result=xmlHttp.responseText;\r\n");
      out.write("\t\t\talert(result);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("function createSendData(){\r\n");
      out.write("\tvar role_name=document.getElementById(\"role_name\").value;\r\n");
      out.write("\tvar role_tel=document.getElementById(\"role_tel\").value;\r\n");
      out.write("\tvar data=\"rolename=\"+role_name+\"&roletel=\"+role_tel;\r\n");
      out.write("\treturn data;\r\n");
      out.write("}\r\n");
      out.write("function getYzm(){\r\n");
      out.write("\tvar role_name=document.getElementById(\"role_name\").value;\r\n");
      out.write("\tvar role_tel=document.getElementById(\"role_tel\").value;\r\n");
      out.write("\tif(role_name==null||role_name==\"\"){\r\n");
      out.write("\t\talert(\"请输入用户名\");\r\n");
      out.write("\t}else{\r\n");
      out.write("\t\t if(role_tel==null||role_tel==\"\"){\r\n");
      out.write("\t\t\talert(\"请输入手机号码\");\r\n");
      out.write("\t\t}else{ \r\n");
      out.write("\t\t\tcreateXmlHttpRequest();\r\n");
      out.write("\t\t\tvar url=\"/ShoppingMall/store/getyzm.do\";\r\n");
      out.write("\t\t\txmlHttp.open(\"get\", url+\"?\"+createSendData());\r\n");
      out.write("\t\t\txmlHttp.setRequestHeader(\"Content-Type\", \"application/x-www-form-urlencoded\");\r\n");
      out.write("\t\t\txmlHttp.send(null);\r\n");
      out.write("\t\t\txmlHttp.onreadystatechange=handleStateChange();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("function selStoreRegist() {\r\n");
      out.write("\tvar role_name=document.getElementById(\"role_name\").value;\r\n");
      out.write("\tvar role_pwd=document.getElementById(\"role_pwd\").value;\r\n");
      out.write("\tvar linkman_name=document.getElementById(\"linkman_name\").value;\r\n");
      out.write("\tvar role_tel=document.getElementById(\"role_tel\").value;\r\n");
      out.write("\tvar storeLicenseRoute=document.getElementById(\"storeLicenseRoute\").value;\r\n");
      out.write("\tvar storeMenRoute=document.getElementById(\"storeMenRoute\").value;\r\n");
      out.write("\tvar storeImageRoute=document.getElementById(\"storeImageRoute\").value;\r\n");
      out.write("\tif(role_name==null||role_name==\"\"){\r\n");
      out.write("\t\talert(\"请输入用户名\");\r\n");
      out.write("\t}else{\r\n");
      out.write("\t\tif(role_pwd==null||role_pwd==\"\"){\r\n");
      out.write("\t\t\talert(\"请输入密码\");\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\tif(linkman_name==null||linkman_name==\"\"){\r\n");
      out.write("\t\t\t\talert(\"请输入联系人姓名\");\r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t\t\tif(role_tel==null||role_tel==\"\"){\r\n");
      out.write("\t\t\t\t\talert(\"请输入手机号码\");\r\n");
      out.write("\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\tif(storeLicenseRoute==null||storeLicenseRoute==\"\"){\r\n");
      out.write("\t\t\t\t\t\talert(\"请上传营业执照图片\");\r\n");
      out.write("\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\tif(storeMenRoute==null||storeMenRoute==\"\"){\r\n");
      out.write("\t\t\t\t\t\t\talert(\"请上传店主手持身份证图片\");\r\n");
      out.write("\t\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\t\tif(storeImageRoute==null||storeImageRoute==\"\"){\r\n");
      out.write("\t\t\t\t\t\t\t\talert(\"请上传店铺图片\");\r\n");
      out.write("\t\t\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById(\"storeRegist\").enctype='application/x-www-form-urlencoded';\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById(\"storeRegist\").action='/ShoppingMall/store/storeRegist.do';\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById(\"storeRegist\").submit();\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("//上传店铺营业执照照片\r\n");
      out.write("function uploadStoreLicense() {  \r\n");
      out.write("\talert(\"上传店铺营业执照照片\");\r\n");
      out.write("\t\t // 上传设置  \r\n");
      out.write("\tvar options = {  \r\n");
      out.write("    // 规定把请求发送到那个URL  \r\n");
      out.write("    url: \"/ShoppingMall/upload/uploadStoreLicense.do\",  \r\n");
      out.write("    // 请求方式  \r\n");
      out.write("    type: \"post\",  \r\n");
      out.write("    // 服务器响应的数据类型  \r\n");
      out.write("    dataType: \"json\",  \r\n");
      out.write("    // 请求成功时执行的回调函数  \r\n");
      out.write("    success: function(data, status, xhr) {  \r\n");
      out.write("        // 图片显示地址  \r\n");
      out.write("        $(\"#defaultStoreLicense\").attr(\"src\",\"/ShoppingMall/\"+data.path); \r\n");
      out.write("        $(\"#storeLicenseRoute\").attr(\"value\",data.path);\r\n");
      out.write("        alert(data.path);\r\n");
      out.write("        \r\n");
      out.write("    }  \r\n");
      out.write("};  \r\n");
      out.write("\r\n");
      out.write("$(\"#uploadStoreLicense\").ajaxSubmit(options);  \r\n");
      out.write("}  \r\n");
      out.write("\r\n");
      out.write("//上传店主手持身份证图片\r\n");
      out.write("function uploadStoreMen() {  \r\n");
      out.write("\talert(\"上传店主手持身份证照片\");\r\n");
      out.write("\t\t // 上传设置  \r\n");
      out.write("\tvar options = {  \r\n");
      out.write("    // 规定把请求发送到那个URL  \r\n");
      out.write("    url: \"/ShoppingMall/upload/uploadStoreMenImage.do\",  \r\n");
      out.write("    // 请求方式  \r\n");
      out.write("    type: \"post\",  \r\n");
      out.write("    // 服务器响应的数据类型  \r\n");
      out.write("    dataType: \"json\",  \r\n");
      out.write("    // 请求成功时执行的回调函数  \r\n");
      out.write("    success: function(data, status, xhr) {  \r\n");
      out.write("        // 图片显示地址  \r\n");
      out.write("        $(\"#defaultStoreMen\").attr(\"src\",\"/ShoppingMall/\"+data.path); \r\n");
      out.write("        $(\"#storeMenRoute\").attr(\"value\",data.path);\r\n");
      out.write("        alert(data.path);\r\n");
      out.write("        \r\n");
      out.write("    }  \r\n");
      out.write("};  \r\n");
      out.write("\r\n");
      out.write("$(\"#uploadStoreMen\").ajaxSubmit(options);  \r\n");
      out.write("}  \r\n");
      out.write("\r\n");
      out.write("//上传店内图片\r\n");
      out.write("function uploadStoreImage() {  \r\n");
      out.write("\talert(\"上传店内照片\");\r\n");
      out.write("\t\t // 上传设置  \r\n");
      out.write("\tvar options = {  \r\n");
      out.write("    // 规定把请求发送到那个URL  \r\n");
      out.write("    url: \"/ShoppingMall/upload/uploadStoreImage.do\",  \r\n");
      out.write("    // 请求方式  \r\n");
      out.write("    type: \"post\",  \r\n");
      out.write("    // 服务器响应的数据类型  \r\n");
      out.write("    dataType: \"json\",  \r\n");
      out.write("    // 请求成功时执行的回调函数  \r\n");
      out.write("    success: function(data, status, xhr) {  \r\n");
      out.write("        // 图片显示地址  \r\n");
      out.write("        $(\"#defaultStoreImage\").attr(\"src\",\"/ShoppingMall/\"+data.path); \r\n");
      out.write("        $(\"#storeImageRoute\").attr(\"value\",data.path);\r\n");
      out.write("        alert(data.path);\r\n");
      out.write("        \r\n");
      out.write("    }  \r\n");
      out.write("};  \r\n");
      out.write("\r\n");
      out.write("$(\"#uploadStoreImage\").ajaxSubmit(options);  \r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
